### ISSUE TITLE
Error in the node_modules folder

### ISSUE THREAD

**Issue by rajudevjava** [marcysutton/axe-webdriverjs-demo#3]
@marcysutton I just cloned this project into eclipse and wanted to run test.js .
Before I did that, I did npm install and I got node_modules folder. I see there are errors on sax and selenium-webdriver folders inside node_modules folder. Could you please help me solve this error. Thank you!

**Comment by marcysutton** [comment]
I just ran a fresh install and it worked for me. Can you provide more details?

**Comment by rajudevjava** [comment]
I downloaded this project and imported into eclipse as  General -> Projects from Folder or Archive (not sure if importing this way is right) as I did not find option to import this project as a Javascript project.  PFA screenshot.
![capture](https://user-images.githubusercontent.com/11168455/38905190-f26ebb30-427c-11e8-92b9-288f4080b2b9.PNG)

**Comment by marcysutton** [comment]
Sorry, this project doesn't support Eclipse. I can't control how it handles dependencies. You should try a more Javascript-friendly IDE like Sublime Text, Visual Studio Code or Atom.

**Comment by rajudevjava** [comment]
@marcysutton Thanks! I now have the project set up in Sublime Text. I do have  2 questions. 
1. When I try to run in cmd using npm test, I could only trigger custom-rule-test.js and no other test. How can I run test.js or remote-url-test.js ?
2. Running custom-rule-test.js - A blank chrome browser opens up but I get below error in cmd 
![capture](https://user-images.githubusercontent.com/11168455/38944600-5627b458-4302-11e8-8a6e-8ae888153ee8.PNG)

**Comment by marcysutton** [comment]
1. the test file is hard-coded in the test script in package.json
2. you'll have to extend timeouts in Jasmine, there's an example in `remote-url-test.js`

**Comment by rajudevjava** [comment]
@marcysutton I can trigger test.js. But, even after the wait time, it wouldn't navigate to the url I specified. Below is the screenshot of the error. It is only a blank chrome window opening. 
![capture](https://user-images.githubusercontent.com/11168455/38953270-34962b2a-431c-11e8-95fd-bb5eb5698838.PNG)
